version: '3.8'
services:
    nginx:
        build: docker/nginx
        restart: always
        environment:
            - TZ=$TZ
            - LANG=$LANG
        ports:
            - "${NGINX_PORT}:80"
        volumes:
            - "./app:${APP_DIR}"
            - "./config/nginx/nginx.conf:/etc/nginx/nginx.conf"
            - "./config/nginx/conf.d:/etc/nginx/conf.d"
            - "./logs/nginx:/var/log/nginx"
        links:
            - php
    php:
        build: docker/php-fpm
        restart: always
        environment:
            - TZ=$TZ
            - LANG=$LANG
        volumes:
            - "./app:${APP_DIR}"
            - "./config/php-fpm/php/php.ini:/usr/local/etc/php/php.ini"
            - "./config/php-fpm/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf"
            - "./config/php-fpm/ssh:/root/.ssh/"
            - "./config/php-fpm/supervisor/supervisord.conf:/etc/supervisor/supervisord.conf"
            - "./config/php-fpm/supervisor/conf.d:/etc/supervisor/conf.d/"
            - "./logs/supervisor:/var/log/supervisor"
            - "./logs/php-fpm:/var/log/php-fpm"
        expose:
            - "9000"
    mysql:
        build: docker/mysql
        restart: always
        ports:
            - "${MYSQL_PORT}:3306"
        expose:
            - 3306
        environment:
            - TZ=$TZ
            - LANG=$LANG
            - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
            - MYSQL_DATABASE=$MYSQL_DATABASE
            - MYSQL_USER=$MYSQL_USER
            - MYSQL_PASSWORD=$MYSQL_PASSWORD
        volumes:
            - "./data/mysql:/var/lib/mysql"
            - "./config/mysql/my.cnf:/etc/mysql/my.cnf"
    redis:
        build: docker/redis
        restart: always
        ports:
            - "${REDIS_PORT}:6379"
        expose:
            - 6379
        environment:
            - TZ=$TZ
            - LANG=$LANG
        volumes:
            - "./data/redis:/data"
            - "./config/redis/redis.conf:/usr/local/etc/redis/redis.conf"
